# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_hash', models.CharField(max_length=6)),
                ('datetime', models.DateTimeField()),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('long_hash', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('snapshot', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('path_on_server', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=128)),
                ('ssh', models.CharField(blank=True, max_length=500)),
                ('avatar', models.CharField(max_length=300)),
                ('backup_email', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lit.Repository')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lit.User')),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='long_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit.Files'),
        ),
        migrations.AddField(
            model_name='commit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit.User'),
        ),
        migrations.AddField(
            model_name='branchcommit',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit.Commit'),
        ),
        migrations.AddField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit.Repository'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermissions',
            unique_together=set([('user', 'repository')]),
        ),
    ]
