# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='repositories',
            field=models.ManyToManyField(related_name='users', through='lit.UserPermissions', to='lit.Repository'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit.Repository'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit.User'),
        ),
    ]
