# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0002_auto_20171115_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='backup_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ssh',
        ),
    ]
