# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='repositories',
            field=models.ManyToManyField(related_name='users', through='permissions.UserPermissions', to='repositories.Repository'),
        ),
        migrations.DeleteModel(
            name='UserPermissions',
        ),
    ]
