# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_file_path),
        ),
    ]
