language: python

cache: pip

python:
  - "3.4"

install:
    - pip install flake8
    - pip install -r requirements.txt

before_script:
    # stop the build if there are Python syntax errors or undefined names
    - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - time flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

script:
    - python manage.py test

notifications:
  email:
    recipients:
      - maxkrivich@gmail.com
    on_success: always
    on_failure: always

branches:
  only:
  - master
  - dev