# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repositories', '0003_auto_20171223_2235'),
        ('permissions', '0002_userpermissions_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermissions',
            unique_together=set([('user', 'repository')]),
        ),
    ]
