# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_hash', models.CharField(max_length=6)),
                ('commit_time', models.DateTimeField()),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('long_hash', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('snapshot', models.CharField(max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='long_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commits.Files'),
        ),
    ]
