# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('default_branch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='default', to='branches.Branch')),
            ],
        ),
    ]
